apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-in-cluster
  namespace: kube-system
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - name: local
      cluster:
        server: https://colemick5a31cf08.k8s.mickens.xyz:443
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lSQUttMXYzRHdxeEt1c2dTblY1YTczdWt3RFFZSktvWklodmNOQVFFTEJRQXcKSlRFUk1BOEdBMVVFQ2hNSVltOXZkR3QxWW1VeEVEQU9CZ05WQkFNVEIydDFZbVV0WTJFd0hoY05NVGN4TWpFMApNREV3T0RNMldoY05NVGd4TWpFME1ERXdPRE0yV2pBbE1SRXdEd1lEVlFRS0V3aGliMjkwYTNWaVpURVFNQTRHCkExVUVBeE1IYTNWaVpTMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLK0oKQzRxMzN4WjhMN0pTWG1TajVpRE1zVktnWU9KT1hpVFVUV3NUdDdrcmFwSmR1bVlSanBOSzJQVnJORjlTdVlTUApsTytXOEtnOWk0SEJCM0pENXAybmcrdzBUV0d5WWthTWxNQ2VzQWhERFlZRlpJRldZR2NNQWRvaUMyMGhNQmNvCk4xMThsSkV2SWI0MEVyV3lUQmt0b2lOSDNleUc5Q3BZd0E5MEg5WStQcXIwc3BCbjA2c3Q2ZkRsZ1JiTjRoQmIKTDdLLzBlbXU5ZXF4aHprSnUyaWwzMEo5Q0lvQUdnKzFCNjcxczVEbXlWUHV1QTdTRENzNVZJbFkzeHU3dEVlcAo0TWYweXZtMGt1ZmFFZzV2S1JFMVZ2b2x5d3dEYS9RWU5tTnlVYWJtQ0RqN1Y3SGdaY3YvQVlYSE53bGJ4M2YxCmUzRnM0ZlBjbVFvYWk3WFpCUk1DQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIKL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkNuTDNLM3U5cmF2bG55ak1HbHdyR2gveE1BUk1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUJmbm44dFY1TUhOQWRrbGpHWW83djIvN1VWT1RmZ1BxT1RvSWJYajR1VUxOWTloaDhsCkZiVklnczVFcU5BNURqWHhtZlJkSWhiVzRzWVlNTDUxcGRKVk1NSDhZWnV6ZTdway8ycXhRNUo4KzZzTFpQNFkKcEcxUkdBd0FNeXB5WldaTFJORlJKTXVlMVZ5OHVvWXZLT1JGeUpGQ1MweWFIdDhaZDZpSU9TQnAxQXA0RExaSgpRL25VU2JPdXR4eGpXVGwvMVNCZkhGS0w3ZU1VeEZKMWJPRXFYQjFGYUVVZlNIRld2ZU5BZXlwaTVTTCtkaWI1CncvSUV3UExqVytJNGxST1k1eHpEN2x0UWFTVVNwbGVBYmdrcVM5eFJVRlhpVWx3K0lkWjBESTczbXROYzVuOVEKdFMxenFET0ZZeUNPNng3NXE3VjJZR0UxK1RJc09iNnhYbDJPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    users:
    - name: service-account
      user:
        # Use service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: local
        user: service-account
